name: bright shiny design objects
favicon: null
layout_spectrum: 0.000631662318482995
typography_spectrum: 0.31737983878701925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0058a8'
    - '#01b6c7'
    - '#fffae7'
    - '#fec200'
    - '#e73511'
  brandStrength: 0.5
  lightness: 0.10473953699693084
  saturation: 0.6875
  rhythmicContrast: 0.20016983500681818
purpose: []
